### ISSUE TITLE
idgl.yml

### ISSUE THREAD

**Issue by RichardShea** [hugochan/IDGL#24]
When I run `python main.py -config config/cora/idgl.yml`, I get the following error:

_Traceback (most recent call last):
  File "main.py", line 123, in <module>
    config = get_config(cfg['config'])
  File "main.py", line 58, in get_config
    config = yaml.load(setting)
TypeError: load() missing 1 required positional argument: 'Loader'_

**Comment by Junseok0207** [comment]
This is the problem caused by the discrepancy on yaml version.
you can solve this error by changing the following

```
config = yaml.full_load(setting)
```
